### ISSUE TITLE
Get upstairs toilet working again

### ISSUE THREAD

**Issue by bkeating** [bkeating/3057MainSt#1]
Benett flushed the toilet and heard a big 'thunk' sound after which we noticed the sewage stack leaking on the basement stairs. I cut open the wall around where we found leaking, but it seems further up. The idea now is to pull the toilet off it's base and see if the piping slipped off around where the toilet is connected--this seems possible as Benett said he definitely heard a loud bang. If there is nothing obvious here, the leaking may be further down, somewhere between both ends. In which case, that means we need to rip up the kitchen ceiling. 

1. Drain toilet
2. Unmount toilet
3. Examine piping
4. Hopefully spot the problem
5. ...
6. Put toilet back in place

**Comment by dsilvers** [comment]
💩

**Comment by bkeating** [comment]
This 💩  is 🍌🍌 🍌 !

**Comment by cgsmith** [comment]
Is this issue still not fixed yet? I submitted a PR years ago!!!

**Comment by dsilvers** [comment]
💩

**Comment by cgsmith** [comment]
💩

**Comment by dsilvers** [comment]
🚽 💥🔨
